name: その他
description: その他機能に直接関わらないタスクのissueテンプレート
labels:
  - chore
body:
  - type: input
    attributes:
      label: タスク内容
      description: |
        - 対応する作業内容を記載してください
    validations:
      required: true
  - type: textarea
    attributes:
      label: 詳細内容
      description: |
        - 詳細な作業内容がわかるよう記載してください
    validations:
      required: true
